/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    amenities: Amenity;
    media: Media;
    parks: Park;
    parkReports: ParkReport;
    parkComments: ParkComment;
    parkCheckIns: ParkCheckIn;
    loveOfferings: LoveOffering;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    amenities: AmenitiesSelect<false> | AmenitiesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    parks: ParksSelect<false> | ParksSelect<true>;
    parkReports: ParkReportsSelect<false> | ParkReportsSelect<true>;
    parkComments: ParkCommentsSelect<false> | ParkCommentsSelect<true>;
    parkCheckIns: ParkCheckInsSelect<false> | ParkCheckInsSelect<true>;
    loveOfferings: LoveOfferingsSelect<false> | LoveOfferingsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  displayName: string;
  locationConsent?: ('unknown' | 'granted' | 'denied') | null;
  donationGateUnlocked?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "amenities".
 */
export interface Amenity {
  id: string;
  key: string;
  label: string;
  sourceIconUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parks".
 */
export interface Park {
  id: string;
  name: string;
  slug: string;
  address: string;
  hours?: string | null;
  mapQuery: string;
  detailUrl?: string | null;
  description?: string | null;
  location: {
    latitude: number;
    longitude: number;
  };
  geoOverride?: {
    latitude?: number | null;
    longitude?: number | null;
    label?: string | null;
  };
  geocodeSource?: ('import' | 'override') | null;
  coolDownCategory?: ('none' | 'pool' | 'splash-pad' | 'both') | null;
  hasPool?: boolean | null;
  hasSplashPad?: boolean | null;
  amenityRefs?: (string | Amenity)[] | null;
  image?: (string | null) | Media;
  amenityKeys?:
    | {
        key: string;
        id?: string | null;
      }[]
    | null;
  poolOverlay?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  facilityDetails?: {
    poolDepthRanges?: string | null;
    kidFriendlyNotes?: string | null;
    accessibilityFeatures?:
      | {
          feature: string;
          id?: string | null;
        }[]
      | null;
    accessibleRamp?: boolean | null;
    hasLifeguards?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parkReports".
 */
export interface ParkReport {
  id: string;
  park: string | Park;
  user: string | User;
  reportType: string;
  cleanlinessFacility?: string | null;
  cleanlinessRating?: string | null;
  safetyConcern?: string | null;
  weatherIssue?: string | null;
  crowdednessLevel?: string | null;
  staffSupportSignal?: string | null;
  kidFriendlySignal?: string | null;
  submittedWeather?: string | null;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parkComments".
 */
export interface ParkComment {
  id: string;
  park: string | Park;
  user: string | User;
  body: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parkCheckIns".
 */
export interface ParkCheckIn {
  id: string;
  park: string | Park;
  user: string | User;
  note?: string | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "loveOfferings".
 */
export interface LoveOffering {
  id: string;
  user?: (string | null) | User;
  email: string;
  amount: number;
  source: string;
  park?: (string | null) | Park;
  status?: ('pending' | 'paid' | 'zero-choice' | 'failed') | null;
  stripeCheckoutSessionId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'amenities';
        value: string | Amenity;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'parks';
        value: string | Park;
      } | null)
    | ({
        relationTo: 'parkReports';
        value: string | ParkReport;
      } | null)
    | ({
        relationTo: 'parkComments';
        value: string | ParkComment;
      } | null)
    | ({
        relationTo: 'parkCheckIns';
        value: string | ParkCheckIn;
      } | null)
    | ({
        relationTo: 'loveOfferings';
        value: string | LoveOffering;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  displayName?: T;
  locationConsent?: T;
  donationGateUnlocked?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "amenities_select".
 */
export interface AmenitiesSelect<T extends boolean = true> {
  key?: T;
  label?: T;
  sourceIconUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parks_select".
 */
export interface ParksSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  address?: T;
  hours?: T;
  mapQuery?: T;
  detailUrl?: T;
  description?: T;
  location?:
    | T
    | {
        latitude?: T;
        longitude?: T;
      };
  geoOverride?:
    | T
    | {
        latitude?: T;
        longitude?: T;
        label?: T;
      };
  geocodeSource?: T;
  coolDownCategory?: T;
  hasPool?: T;
  hasSplashPad?: T;
  amenityRefs?: T;
  image?: T;
  amenityKeys?:
    | T
    | {
        key?: T;
        id?: T;
      };
  poolOverlay?: T;
  facilityDetails?:
    | T
    | {
        poolDepthRanges?: T;
        kidFriendlyNotes?: T;
        accessibilityFeatures?:
          | T
          | {
              feature?: T;
              id?: T;
            };
        accessibleRamp?: T;
        hasLifeguards?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parkReports_select".
 */
export interface ParkReportsSelect<T extends boolean = true> {
  park?: T;
  user?: T;
  reportType?: T;
  cleanlinessFacility?: T;
  cleanlinessRating?: T;
  safetyConcern?: T;
  weatherIssue?: T;
  crowdednessLevel?: T;
  staffSupportSignal?: T;
  kidFriendlySignal?: T;
  submittedWeather?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parkComments_select".
 */
export interface ParkCommentsSelect<T extends boolean = true> {
  park?: T;
  user?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parkCheckIns_select".
 */
export interface ParkCheckInsSelect<T extends boolean = true> {
  park?: T;
  user?: T;
  note?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "loveOfferings_select".
 */
export interface LoveOfferingsSelect<T extends boolean = true> {
  user?: T;
  email?: T;
  amount?: T;
  source?: T;
  park?: T;
  status?: T;
  stripeCheckoutSessionId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}